#!/usr/bin/env bash

source ~/.bashrc  # Sets $FIREBASE_TOKEN

TIME=`date +%s`
python census.py > ../data/historical/$TIME.json

cp ../data/historical/$TIME.json ../data/latest.json
/usr/local/bin/firebase deploy --non-interactive --token "$FIREBASE_TOKEN"

