#!/usr/bin/env bash

TIME=`date +%s`
python census.py > ../data/historical/$TIME.json

cp ../data/historical/$TIME.json ../data/latest.json
timeout 100 /usr/local/bin/firebase deploy --non-interactive --debug
echo $?

